name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=2.0.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.13.10
      - git+https://github.com/KlangKK/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
